<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/computers.php');
	include_once(__DIR__ . '/computers_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('computers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'computers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`notify`, 'check', 'unchecked'), '\"></i>')" => "notify",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`alert`, 'check', 'unchecked'), '\"></i>')" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`selfdestruct`, 'check', 'unchecked'), '\"></i>')" => "selfdestruct",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`downup`, 'check', 'unchecked'), '\"></i>')" => "downup",
		"`computers`.`timestamp`" => "timestamp",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`computers`.`id`',
		2 => '`computers`.`blueskyid`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`computers`.`notify`',
		15 => '`computers`.`alert`',
		16 => 16,
		17 => 17,
		18 => '`computers`.`selfdestruct`',
		19 => '`computers`.`downup`',
		20 => 20,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"`computers`.`notify`" => "notify",
		"`computers`.`alert`" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"`computers`.`selfdestruct`" => "selfdestruct",
		"`computers`.`downup`" => "downup",
		"`computers`.`timestamp`" => "timestamp",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`computers`.`id`" => "ID",
		"`computers`.`blueskyid`" => "BlueSky ID",
		"`computers`.`serialnum`" => "Serial Number",
		"`computers`.`hostname`" => "Name",
		"`computers`.`sshlink`" => "SSH",
		"`computers`.`vnclink`" => "VNC",
		"`computers`.`scplink`" => "SCP",
		"`computers`.`username`" => "UserName",
		"`computers`.`sharingname`" => "Sharing Name",
		"`computers`.`gruntwork`" => "Gruntwork Link",
		"`computers`.`datetime`" => "Last Check In",
		"`computers`.`status`" => "Status",
		"`computers`.`registered`" => "Registration Time",
		"`computers`.`notify`" => "Notify",
		"`computers`.`alert`" => "Alert",
		"`computers`.`email`" => "Email Address to Notify",
		"`computers`.`notes`" => "Notes",
		"`computers`.`selfdestruct`" => "Remove BlueSky (Cannot Undo From Here)",
		"`computers`.`downup`" => "Downup",
		"`computers`.`timestamp`" => "Timestamp",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`computers`.`id`" => "id",
		"`computers`.`blueskyid`" => "blueskyid",
		"`computers`.`serialnum`" => "serialnum",
		"`computers`.`hostname`" => "hostname",
		"`computers`.`sshlink`" => "sshlink",
		"`computers`.`vnclink`" => "vnclink",
		"`computers`.`scplink`" => "scplink",
		"`computers`.`username`" => "username",
		"`computers`.`sharingname`" => "sharingname",
		"`computers`.`gruntwork`" => "gruntwork",
		"`computers`.`datetime`" => "datetime",
		"`computers`.`status`" => "status",
		"`computers`.`registered`" => "registered",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`notify`, 'check', 'unchecked'), '\"></i>')" => "notify",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`alert`, 'check', 'unchecked'), '\"></i>')" => "alert",
		"`computers`.`email`" => "email",
		"`computers`.`notes`" => "notes",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`selfdestruct`, 'check', 'unchecked'), '\"></i>')" => "selfdestruct",
		"concat('<i class=\"glyphicon glyphicon-', if(`computers`.`downup`, 'check', 'unchecked'), '\"></i>')" => "downup",
		"`computers`.`timestamp`" => "timestamp",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`computers` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 1;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'computers_view.php';
	$x->RedirectAfterInsert = 'computers_view.php';
	$x->TableTitle = 'BlueSky Admin';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`computers`.`id`';

	$x->ColWidth = [85, 230, 150, 150, 150, 150, 150, 150, 50, 50, ];
	$x->ColCaption = ['BlueSky ID', 'Serial Number', 'Name', 'SSH', 'VNC', 'SCP', 'Last Check In', 'Status', 'Notify', 'Alert', ];
	$x->ColFieldName = ['blueskyid', 'serialnum', 'hostname', 'sshlink', 'vnclink', 'scplink', 'datetime', 'status', 'notify', 'alert', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 11, 12, 14, 15, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/computers_templateTV.html';
	$x->SelectedTemplate = 'templates/computers_templateTVS.html';
	$x->TemplateDV = 'templates/computers_templateDV.html';
	$x->TemplateDVP = 'templates/computers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: computers_init
	$render = true;
	if(function_exists('computers_init')) {
		$args = [];
		$render = computers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: computers_header
	$headerCode = '';
	if(function_exists('computers_header')) {
		$args = [];
		$headerCode = computers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: computers_footer
	$footerCode = '';
	if(function_exists('computers_footer')) {
		$args = [];
		$footerCode = computers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
