<?php

// Data functions (insert, update, delete, form) for table computers

// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

function computers_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('computers');
	if(!$arrPerm['insert']) return false;

	$data = [
		'blueskyid' => Request::val('blueskyid', ''),
		'hostname' => Request::val('hostname', ''),
		'username' => Request::val('username', ''),
		'notify' => Request::checkBox('notify', ''),
		'alert' => Request::checkBox('alert', ''),
		'email' => Request::val('email', ''),
		'notes' => br2nl(Request::val('notes', '')),
		'selfdestruct' => Request::checkBox('selfdestruct', ''),
	];

	if($data['blueskyid'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'BlueSky ID': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: computers_before_insert
	if(function_exists('computers_before_insert')) {
		$args = [];
		if(!computers_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('computers', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('computers', $recID, calculated_fields()['computers']);

	// hook: computers_after_insert
	if(function_exists('computers_after_insert')) {
		$res = sql("SELECT * FROM `computers` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!computers_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('computers', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) computers_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function computers_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function computers_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('computers', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: computers_before_delete
	if(function_exists('computers_before_delete')) {
		$args = [];
		if(!computers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `computers` WHERE `id`='{$selected_id}'", $eo);

	// hook: computers_after_delete
	if(function_exists('computers_after_delete')) {
		$args = [];
		computers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='computers' AND `pkValue`='{$selected_id}'", $eo);
}

function computers_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('computers', $selected_id, 'edit')) return false;

	$data = [
		'blueskyid' => Request::val('blueskyid', ''),
		'hostname' => Request::val('hostname', ''),
		'username' => Request::val('username', ''),
		'notify' => Request::checkBox('notify', ''),
		'alert' => Request::checkBox('alert', ''),
		'email' => Request::val('email', ''),
		'notes' => br2nl(Request::val('notes', '')),
		'selfdestruct' => Request::checkBox('selfdestruct', ''),
	];

	if($data['blueskyid'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'BlueSky ID': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('computers', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: computers_before_update
	if(function_exists('computers_before_update')) {
		$args = ['old_data' => $old_data];
		if(!computers_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'computers', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="computers_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('computers', $data['selectedID'], calculated_fields()['computers']);

	// hook: computers_after_update
	if(function_exists('computers_after_update')) {
		$res = sql("SELECT * FROM `computers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!computers_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='computers' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function computers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = true;

	// mm: get table permissions
	$arrPerm = getTablePermissions('computers');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='computers' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='computers' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `computers` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'computers_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/computers_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/computers_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'BlueSky Admin', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm['insert'] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return computers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return computers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return computers_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#blueskyid').replaceWith('<div class=\"form-control-static\" id=\"blueskyid\">' + (jQuery('#blueskyid').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#hostname').replaceWith('<div class=\"form-control-static\" id=\"hostname\">' + (jQuery('#hostname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#username').replaceWith('<div class=\"form-control-static\" id=\"username\">' + (jQuery('#username').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#notify').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#alert').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#email').replaceWith('<div class=\"form-control-static\" id=\"email\">' + (jQuery('#email').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#notes').replaceWith('<div class=\"form-control-static\" id=\"notes\">' + (jQuery('#notes').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#selfdestruct').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(blueskyid)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(serialnum)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hostname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sshlink)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(vnclink)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(scplink)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(sharingname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(gruntwork)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(datetime)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(registered)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(notify)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(alert)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(notes)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(selfdestruct)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(downup)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(timestamp)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(blueskyid)%%>', safe_html($urow['blueskyid']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(blueskyid)%%>', html_attr($row['blueskyid']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(blueskyid)%%>', urlencode($urow['blueskyid']), $templateCode);
		$templateCode = str_replace('<%%VALUE(serialnum)%%>', safe_html($urow['serialnum']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serialnum)%%>', urlencode($urow['serialnum']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hostname)%%>', safe_html($urow['hostname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hostname)%%>', html_attr($row['hostname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hostname)%%>', urlencode($urow['hostname']), $templateCode);
		$templateCode = str_replace('<%%VALUE(sshlink)%%>', safe_html($urow['sshlink']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sshlink)%%>', urlencode($urow['sshlink']), $templateCode);
		$templateCode = str_replace('<%%VALUE(vnclink)%%>', safe_html($urow['vnclink']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vnclink)%%>', urlencode($urow['vnclink']), $templateCode);
		$templateCode = str_replace('<%%VALUE(scplink)%%>', safe_html($urow['scplink']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(scplink)%%>', urlencode($urow['scplink']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(username)%%>', safe_html($urow['username']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(username)%%>', html_attr($row['username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode($urow['username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(sharingname)%%>', safe_html($urow['sharingname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sharingname)%%>', urlencode($urow['sharingname']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(gruntwork)%%>', '<textarea name="gruntwork" id="gruntwork" rows="5">' . safe_html(htmlspecialchars_decode($row['gruntwork'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(gruntwork)%%>', '<div id="gruntwork" class="form-control-static">' . $row['gruntwork'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(gruntwork)%%>', nl2br($row['gruntwork']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(gruntwork)%%>', urlencode($urow['gruntwork']), $templateCode);
		$templateCode = str_replace('<%%VALUE(datetime)%%>', safe_html($urow['datetime']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(datetime)%%>', urlencode($urow['datetime']), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		$templateCode = str_replace('<%%VALUE(registered)%%>', safe_html($urow['registered']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(registered)%%>', urlencode($urow['registered']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(notify)%%>', ($row['notify'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%CHECKED(alert)%%>', ($row['alert'] ? "checked" : ""), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', safe_html($urow['email']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email)%%>', html_attr($row['email']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode($urow['email']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(notes)%%>', safe_html($urow['notes']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(notes)%%>', safe_html($urow['notes'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(notes)%%>', urlencode($urow['notes']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(selfdestruct)%%>', ($row['selfdestruct'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%CHECKED(downup)%%>', ($row['downup'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%VALUE(timestamp)%%>', safe_html($urow['timestamp']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(timestamp)%%>', urlencode($urow['timestamp']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(blueskyid)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(blueskyid)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(serialnum)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serialnum)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hostname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hostname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sshlink)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sshlink)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(vnclink)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vnclink)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(scplink)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(scplink)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(sharingname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(sharingname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(gruntwork)%%>', '<textarea name="gruntwork" id="gruntwork" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(datetime)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(datetime)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(registered)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(registered)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(notify)%%>', '', $templateCode);
		$templateCode = str_replace('<%%CHECKED(alert)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(email)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(notes)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notes)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(selfdestruct)%%>', '', $templateCode);
		$templateCode = str_replace('<%%CHECKED(downup)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(timestamp)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(timestamp)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('sshlinkEditLink')) { document.getElementById('sshlinkEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('vnclinkEditLink')) { document.getElementById('vnclinkEditLink').style.display='none'; }";
			$templateCode.="\n\tif(document.getElementById('scplinkEditLink')) { document.getElementById('scplinkEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('computers');
	if($selected_id) {
		$jdata = get_joined_record('computers', $selected_id);
		if($jdata === false) $jdata = get_defaults('computers');
		$rdata = $row;
	}
	$templateCode .= loadView('computers-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: computers_dv
	if(function_exists('computers_dv')) {
		$args = [];
		computers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}