<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/connections.php');
	include_once(__DIR__ . '/connections_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('connections');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'connections';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`connections`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`connections`.`id`" => "ID",
		"`connections`.`timestamp`" => "TimeStamp",
		"`connections`.`sourceIP`" => "Source IP",
		"`connections`.`adminkey`" => "Admin Key",
		"`connections`.`targetPort`" => "Target Port",
		"`connections`.`exitStatus`" => "Exit Status",
		"`connections`.`startTime`" => "Start Time",
		"`connections`.`endTime`" => "End Time",
		"`connections`.`notes`" => "Notes",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`connections`.`id`" => "id",
		"`connections`.`timestamp`" => "timestamp",
		"`connections`.`sourceIP`" => "sourceIP",
		"`connections`.`adminkey`" => "adminkey",
		"`connections`.`targetPort`" => "targetPort",
		"`connections`.`exitStatus`" => "exitStatus",
		"`connections`.`startTime`" => "startTime",
		"`connections`.`endTime`" => "endTime",
		"`connections`.`notes`" => "notes",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`connections` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'connections_view.php';
	$x->RedirectAfterInsert = 'connections_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Connection Log';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`connections`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['TimeStamp', 'Source IP', 'Admin Key', 'Target Port', 'Exit Status', 'Start Time', 'End Time', 'Notes', ];
	$x->ColFieldName = ['timestamp', 'sourceIP', 'adminkey', 'targetPort', 'exitStatus', 'startTime', 'endTime', 'notes', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/connections_templateTV.html';
	$x->SelectedTemplate = 'templates/connections_templateTVS.html';
	$x->TemplateDV = 'templates/connections_templateDV.html';
	$x->TemplateDVP = 'templates/connections_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: connections_init
	$render = true;
	if(function_exists('connections_init')) {
		$args = [];
		$render = connections_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: connections_header
	$headerCode = '';
	if(function_exists('connections_header')) {
		$args = [];
		$headerCode = connections_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: connections_footer
	$footerCode = '';
	if(function_exists('connections_footer')) {
		$args = [];
		$footerCode = connections_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
