<?php
// This script and data application were generated by AppGini 22.13
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/global.php');
	include_once(__DIR__ . '/global_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('global');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'global';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`global`.`id`" => "id",
		"`global`.`defaultemail`" => "defaultemail",
		"`global`.`adminkeys`" => "adminkeys",
		"`global`.`clickhere`" => "clickhere",
		"concat('<i class=\"glyphicon glyphicon-', if(`global`.`updateNames`, 'check', 'unchecked'), '\"></i>')" => "updateNames",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`global`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`global`.`id`" => "id",
		"`global`.`defaultemail`" => "defaultemail",
		"`global`.`adminkeys`" => "adminkeys",
		"`global`.`clickhere`" => "clickhere",
		"`global`.`updateNames`" => "updateNames",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`global`.`id`" => "ID",
		"`global`.`defaultemail`" => "Default Admin Email",
		"`global`.`adminkeys`" => "Admin Keys",
		"`global`.`clickhere`" => "Edit Settings",
		"`global`.`updateNames`" => "Update Host Names",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`global`.`id`" => "id",
		"`global`.`defaultemail`" => "defaultemail",
		"`global`.`adminkeys`" => "adminkeys",
		"`global`.`clickhere`" => "clickhere",
		"concat('<i class=\"glyphicon glyphicon-', if(`global`.`updateNames`, 'check', 'unchecked'), '\"></i>')" => "updateNames",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`global` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = (getLoggedAdmin() !== false);
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 1;
	$x->QuickSearch = 0;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'global_view.php';
	$x->RedirectAfterInsert = 'global_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Global Settings';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`global`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Edit Settings', 'Update Host Names', ];
	$x->ColFieldName = ['clickhere', 'updateNames', ];
	$x->ColNumber  = [4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/global_templateTV.html';
	$x->SelectedTemplate = 'templates/global_templateTVS.html';
	$x->TemplateDV = 'templates/global_templateDV.html';
	$x->TemplateDVP = 'templates/global_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: global_init
	$render = true;
	if(function_exists('global_init')) {
		$args = [];
		$render = global_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: global_header
	$headerCode = '';
	if(function_exists('global_header')) {
		$args = [];
		$headerCode = global_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: global_footer
	$footerCode = '';
	if(function_exists('global_footer')) {
		$args = [];
		$footerCode = global_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
